### ISSUE TITLE
Running on x54 ubuntu pc

### ISSUE THREAD

**Issue by KevinRK27** [Qengineering/Face-Recognition-Jetson-Nano#15]
Is it possible to run this on x64 ubuntu pc?

**Comment by Qengineering** [comment]
Sure!
First ,you have to install ncnn on your x64 system. (See [here](https://github.com/Tencent/ncnn) how to install)
Next, install OpenCV if not already running.
At last download the project and alter the project directories to your situation in the [code::blocks project](https://github.com/Qengineering/Face-Recognition-Jetson-Nano/blob/main/FaceRecognition.cbp) file.

**Comment by KevinRK27** [comment]
I've successfully run it on x64 pc thanks! 
how many fps will i get if i run it on jetson xavier?

**Comment by Qengineering** [comment]
No idea, you have to try.
