### ISSUE TITLE
Fatal signal 11 (SIGSEGV),

### ISSUE THREAD

**Issue by kikirizki** [Qengineering/Face-Recognition-Jetson-Nano#7]
Hi thanks for your amazing work, I tried to run arcface on android, but it I keep getting `Fatal signal 11 (SIGSEGV)`. If I change the output Blob name from `fc1` to `output` the error does not show up but it return empty tensor

**Comment by Qengineering** [comment]
Sorry @kikirizki, I'm afraid I can't be of any help on this. I haven't written or testes the software on android. Both, MNN and ncnn can run on android, something you surely knew.

**Comment by kikirizki** [comment]
Hi @Qengineering , Thank you for your prompt response, would you mind point me out about how did you convert the weight from the original arcface to` .param `and `.bin` file. I will try to convert it myself, thank you.

**Comment by Qengineering** [comment]
A part of the project I've copied from [GitHub](https://github.com/XinghaoChen9/LiveFaceReco_RaspberryPi) as listed in the _Thanks_. Here the model was already converted.
On his turn Xinghao has used this GitHub [repo](https://github.com/deepinsight/insightface). There is a conversation about [training](https://github.com/deepinsight/insightface/issues/214)

**Comment by kikirizki** [comment]
@Qengineering Thank you for help, I will close this issue
